INSERT INTO Season (name) VALUES
('Early January'),
('Late January'),
('Early February'),
('Late February'),
('Early March'),
('Late March'),
('Early April'),
('Late April'),
('Early May'),
('Late May'),
('Early June'),
('Late June'),
('Early July'),
('Late July'),
('Early August'),
('Late August'),
('Early September'),
('Late September'),
('Early October'),
('Late October'),
('Early November'),
('Late November'),
('Early December'),
('Late December');

-- Sampling of states for demonstration purposes
INSERT INTO location (abbr, name) VALUES
-- ('AK','Alaska'),
-- ('AL','Alabama'),
-- ('AR','Arkansas'),
-- ('AZ','Arizona'),
('CA','California'),
-- ('CO','Colorado'),
-- ('CT','Connecticut'),
-- ('DC', 'Washington DC'),
-- ('DE','Delaware'),
('FL','Florida'),
-- ('GA','Georgia'),
-- ('HI','Hawaii'),
-- ('IA','Iowa'),
-- ('ID','Idaho'),
-- ('IL','Illinois'),
-- ('IN','Indiana'),
-- ('KS','Kansas'),
-- ('KY','Kentucky'),
-- ('LA','Louisiana'),
('MA','Massachusetts'),
-- ('MD','Maryland'),
-- ('ME','Maine'),
-- ('MI','Michigan'),
('MN','Minnesota'),
-- ('MO','Missouri'),
-- ('MS','Mississippi'),
-- ('MT','Montana'),
-- ('NC','North Carolina'),
-- ('ND','North Dakota'),
-- ('NE','Nebraska'),
-- ('NH','New Hampshire'),
-- ('NJ','New Jersey'),
-- ('NM','New Mexico'),
-- ('NV','Nevada'),
-- ('NY','New York'),
-- ('OH','Ohio'),
-- ('OK','Oklahoma'),
-- ('OR','Oregon'),
-- ('PA','Pennsylvania'),
-- ('RI','Rhode Island'),
-- ('SC','South Carolina'),
-- ('SD','South Dakota'),
-- ('TN','Tennessee'),
('TX','Texas'),
-- ('UT','Utah'),
-- ('VA','Virginia'),
-- ('VT','Vermont'),
('WA','Washington');
-- ('WI','Wisconsin'),
-- ('WV','West Virginia'),
-- ('WY','Wyoming');