INSERT INTO Ingredient (id, name, root) VALUES
(1, 'carrots', 'carrot'),
(2, 'celery', 'celery'),
(3, 'celery root', 'celery root'),
(4, 'chard', 'chard'),
(5, 'chicories', 'chicor'),
(6, 'cilantro', 'cilantro'),
(7, 'collard greens', 'collard green'),
(8, 'endive', 'endive'),
(9, 'fennel', 'fennel'),
(10, 'green onions', 'green onion'),
(11, 'horseradish', 'horseradish'),
(12, 'kale', 'kale'),
(13, 'kohlrabi', 'kohlrabi'),
(14, 'mint', 'mint'),
(15, 'mustard greens', 'mustard green'),
(16, 'oregano', 'oregano'),
(17, 'parsley', 'parsley'),
(18, 'parsnips', 'parsnip'),
(19, 'pecans', 'pecan'),
(20, 'radicchio', 'radicchio'),
(21, 'rapini', 'rapini'),
(22, 'rosemary', 'rosemary'),
(23, 'sage', 'sage'),
(24, 'sprouts', 'sprout'),
(25, 'sunchokes', 'sunchok'),
(26, 'tarragon', 'tarragon'),
(27, 'thyme', 'thyme'),
(28, 'turnips', 'turnip'),
(29, 'yams', 'yam'),
(30, 'fava beans', 'fava bean'),
(31, 'rhubarb', 'rhubarb'),
(32, 'shallots', 'shallot'),
(33, 'asparagus', 'asparagu'),
(34, 'chives', 'chiv'),
(35, 'mushrooms', 'mushroom'),
(36, 'nettles', 'nettl'),
(37, 'pea shoots', 'pea shoot'),
(38, 'radishes', 'radish'),
(39, 'arugula', 'arugula'),
(40, 'cauliflower', 'cauliflower'),
(41, 'lettuce', 'lettuce'),
(42, 'strawberries', 'strawberr'),
(43, 'leeks', 'leek'),
(44, 'watercress', 'watercres'),
(45, 'beets', 'beet'),
(46, 'bok choy', 'bok choy'),
(47, 'cabbage', 'cabbage'),
(48, 'lamb''s quarters', 'lamb''s quarter'),
(49, 'onions', 'onion'),
(50, 'peas', 'pea'),
(51, 'purslane', 'purslane'),
(52, 'snap peas', 'snap pea'),
(53, 'snow peas', 'snow pea'),
(54, 'sorrel', 'sorrel'),
(55, 'spinach', 'spinach'),
(56, 'summer squash', 'summer squash'),
(57, 'zucchini', 'zucchini'),
(58, 'basil', 'basil'),
(59, 'garlic scapes', 'garlic scap'),
(60, 'black-eyed peas', 'black-eyed pea'),
(61, 'blueberries', 'blueberr'),
(62, 'broccoli', 'broccoli'),
(63, 'corn', 'corn'),
(64, 'cucumbers', 'cucumber'),
(65, 'eggplant', 'eggplant'),
(66, 'green beans', 'green bean'),
(67, 'nectarines', 'nectarin'),
(68, 'peaches', 'peach'),
(69, 'potatoes', 'potato'),
(70, 'cherries', 'cherr'),
(71, 'chili peppers', 'chili pepper'),
(72, 'edamame', 'edamame'),
(73, 'garlic', 'garlic'),
(74, 'ground cherries', 'ground cherr'),
(75, 'melons', 'melon'),
(76, 'peppers', 'pepper'),
(77, 'tomatillos', 'tomatillo'),
(78, 'tomatoes', 'tomato'),
(79, 'watermelon', 'watermelon'),
(80, 'blackberries', 'blackberr'),
(81, 'boysenberries', 'boysenberr'),
(82, 'brambles', 'brambl'),
(83, 'cantaloupe', 'cantaloupe'),
(84, 'okra', 'okra'),
(85, 'raspberries', 'raspberr'),
(86, 'gooseberries', 'gooseberr'),
(87, 'lavender', 'lavender'),
(88, 'lima beans', 'lima bean'),
(89, 'plums', 'plum'),
(90, 'shell beans', 'shell bean'),
(91, 'apples', 'appl'),
(92, 'figs', 'fig'),
(93, 'grapes', 'grap'),
(94, 'sweet potatoes', 'sweet potato'),
(95, 'asian pears', 'asian pear'),
(96, 'pears', 'pear'),
(97, 'winter squash', 'winter squash'),
(98, 'persimmons', 'persimmon'),
(99, 'pumpkin', 'pumpkin'),
(100, 'rutabaga', 'rutabaga'),
(101, 'brussels sprouts', 'brussels sprout'),
(102, 'cardoons', 'cardoon'),
(103, 'citrus', 'citru'),
(104, 'clementines', 'clementin'),
(105, 'grapefruit', 'grapefruit'),
(106, 'lemons', 'lemon'),
(107, 'mandarins', 'mandarin'),
(108, 'oranges', 'orang'),
(109, 'pummelo', 'pummelo'),
(110, 'tangerines', 'tangerin'),
(111, 'quince', 'quince'),
(112, 'apricots', 'apricot'),
(113, 'currants', 'currant'),
(114, 'salsify', 'salsify'),
(115, 'pistachios', 'pistachio'),
(116, 'dates', 'dat'),
(117, 'nopales', 'nopal'),
(118, 'morels', 'morel'),
(119, 'avocados', 'avocado'),
(120, 'kiwi', 'kiwi'),
(121, 'artichokes', 'artichok'),
(122, 'fiddleheads', 'fiddlehead'),
(123, 'chickpeas', 'chickpea'),
(124, 'lemongrass', 'lemongras'),
(125, 'mangoes', 'mango'),
(126, 'burdock', 'burdock'),
(127, 'ginger', 'ginger'),
(128, 'olives', 'oliv'),
(129, 'pomegranates', 'pomegranat'),
(130, 'chestnuts', 'chestnut'),
(131, 'ramps', 'ramp'),
(132, 'cranberries', 'cranberr'),
(133, 'bananas', 'banana'),
(134, 'jicama', 'jicama'),
(135, 'peanuts', 'peanut'),
(136, 'taro', 'taro'),
(137, 'papaya', 'papaya'),
(138, 'pineapple', 'pineapple'),
(139, 'butter', 'butter'),
(140, 'parmesan', 'parmesan'),
(141, 'arborio rice', 'arborio rice'),
(142, 'light mayonnaise', 'light mayonnaise'),
(143, 'Appleton Farms Center Cut Bacon', 'Appleton Farms Center Cut Bacon'),
(144, 'soft taco-size low carb flour tortilla', 'soft taco-size low carb flour tortilla'),
(145, '(1 oz) Never Any! Oven Roasted Turkey', '(1 oz) Never Any! Oven Roasted Turkey'),
(146, 'orecchiette pasta', 'orecchiette pasta'),
(147, 'less sodium chicken broth', 'less sodium chicken broth'),
(148, 'grated Parmigiano Reggiano', 'grated Parmigiano Reggiano'),
(149, 'pure maple syrup', 'pure maple syrup'),
(150, 'reduced sodium soy sauce', 'reduced sodium soy sauce'),
(151, 'sriracha hot sauce', 'sriracha hot sauce'),
(152, 'wild salmon fillets', 'wild salmon fillet'),
(153, 'low sodium soy sauce or use gf soy sauce*', 'low sodium soy sauce or use gf soy sauce*'),
(154, 'chicken broth*', 'chicken broth*'),
(155, 'mirin', 'mirin'),
(156, 'sugar', 'sugar'),
(157, 'sesame oil', 'sesame oil'),
(158, 'canola oil divided', 'canola oil divided'),
(159, 'chicken breast', 'chicken breast'),
(160, 'sesame seeds and scallion for garnish', 'sesame seeds and scallion for garnish'),
(161, 'kosher salt', 'kosher salt'),
(162, '93% ground turkey', '93% ground turkey'),
(163, 'quick cooking oatmeal*', 'quick cooking oatmeal*'),
(164, 'Kansas City Style BBQ Sauce', 'Kansas City Style BBQ Sauce'),
(165, 'large egg', 'large egg'),
(166, 'dried marjoram', 'dried marjoram'),
(168, 'cooking spray', 'cooking spray'),
(169, 'diced ham steak or leftover ham', 'diced ham steak or leftover ham'),
(170, 'fresh grated Swiss cheese', 'fresh grated Swiss cheese'),
(171, '2% milk', '2% milk'),
(172, 'half & half cream', 'half & half cream'),
(173, 'of nutmeg', 'of nutmeg'),
(174, 'low fat sour cream', 'low fat sour cream'),
(175, 'smoked ham hock', 'smoked ham hock'),
(176, 'chicken broth', 'chicken broth'),
(177, 'water', 'water'),
(178, 'whole wheat or gluten-free seasoned breadcrumbs', 'whole wheat or gluten-free seasoned breadcrumb'),
(179, 'cheddar cheese', 'cheddar cheese'),
(180, 'toothpicks', 'toothpick'),
(181, 'all-purpose flour', 'all-purpose flour'),
(182, 'white wine', 'white wine'),
(183, 'whole milk', 'whole milk'),
(184, 'skinless hot-smoked salmon', 'skinless hot-smoked salmon'),
(185, 'trimmed', 'trimmed'),
(186, 'bay leaves', 'bay leav'),
(187, 'reduced-fat sour cream', 'reduced-fat sour cream'),
(188, 'fish fillets', 'fish fillet'),
(189, 'lime juice', 'lime juice'),
(190, 'prepared marinara sauce', 'prepared marinara sauce'),
(191, 'grated Parmesan cheese', 'grated Parmesan cheese'),
(192, 'thin chicken cutlets', 'thin chicken cutlet'),
(193, 'fresh mozzarella cheese', 'fresh mozzarella cheese'),
(194, 'scallions', 'scallion'),
(195, 'lime wedges', 'lime wedg'),
(196, 'cumin', 'cumin'),
(197, 'chipotle chile powder', 'chipotle chile powder'),
(198, 'steel cut oats', 'steel cut oat'),
(199, 'cinnamon sticks', 'cinnamon stick'),
(200, 'milk of your choice', 'milk of your choice'),
(201, 'ground cinnamon', 'ground cinnamon'),
(202, 'NeverAny! Fresh ABF Chicken Breasts', 'NeverAny! Fresh ABF Chicken Breast'),
(203, 'garam masala', 'garam masala'),
(204, 'ground turmeric', 'ground turmeric'),
(205, 'chili powder', 'chili powder'),
(206, 'Carlini Ghee Clarified Butter', 'Carlini Ghee Clarified Butter'),
(207, 'packages', 'packag'),
(208, '3 lb chicken, washed and dried, fat removed', '3 lb chicken, washed and dried, fat removed'),
(209, 'dried herbes de Provence', 'dried herbes de Provence'),
(210, 'Reynolds Wrap Heavy-Duty Aluminum Foil', 'Reynolds Wrap Heavy-Duty Aluminum Foil'),
(211, 'links', 'link'),
(212, 'whole wheat French bread or baguette', 'whole wheat French bread or baguette'),
(213, 'turkey breast', 'turkey breast'),
(214, 'kosher', 'kosher'),
(215, 'dry turkey or poultry seasoning', 'dry turkey or poultry seasoning'),
(216, 'Fit & Active 93% Lean Ground Turkey', 'Fit & Active 93% Lean Ground Turkey'),
(217, 'SimplyNature Organic Low Sodium Free Range Chicken Broth*', 'SimplyNature Organic Low Sodium Free Range Chicken Broth*'),
(218, 'shredded Fit & Active 2% Milk Sharp Cheddar Cheese*', 'shredded Fit & Active 2% Milk Sharp Cheddar Cheese*'),
(219, 'Juice of 1 lime', 'Juice of 1 lime'),
(220, 'smoked paprika', 'smoked paprika'),
(221, 'large peeled', 'large peeled'),
(222, 'cooked brown rice', 'cooked brown rice'),
(223, 'salt', 'salt'),
(224, 'Juice of ½ lime', 'Juice of ½ lime'),
(225, 'small', 'small'),
(226, 'fat free Greek yogurt', 'fat free Greek yogurt'),
(227, 'taco seasoning', 'taco seasoning'),
(228, 'canned black beans', 'canned black bean'),
(229, 'mild or spicy salsa', 'mild or spicy salsa'),
(230, 'reduced fat Mexican cheese blend', 'reduced fat Mexican cheese blend'),
(231, 'all-purpose or gluten-free flour', 'all-purpose or gluten-free flour'),
(232, 'paprika', 'paprika'),
(233, 'ground turkey or chicken', 'ground turkey or chicken'),
(234, 'One 15-ounce can white beans', 'One 15-ounce can white bean'),
(235, 'reduced-sodium chicken or vegetable broth', 'reduced-sodium chicken or vegetable broth'),
(236, 'cocoa powder', 'cocoa powder'),
(237, 'Avocado', 'Avocado'),
(238, ' Sour cream or Nonfat plain Greek yogurt', ' Sour cream or Nonfat plain Greek yogurt'),
(239, ' Cilantro', ' Cilantro'),
(240, 'dried pinto beans', 'dried pinto bean'),
(241, '93% lean ground turkey', '93% lean ground turkey'),
(242, 'bay leaf', 'bay leaf'),
(243, 'unseasoned rice vinegar', 'unseasoned rice vinegar'),
(244, 'raw honey', 'raw honey'),
(245, 'boneless', 'boneles'),
(246, 'chopped roasted', 'chopped roasted'),
(247, 'flour', 'flour'),
(248, 'chicken stock', 'chicken stock'),
(249, 'baking soda', 'baking soda'),
(250, 'vanilla extract', 'vanilla extract'),
(251, 'raisins', 'raisin'),
(252, 'honey', 'honey'),
(253, 'quick oats', 'quick oat'),
(254, 'cinnamon', 'cinnamon'),
(255, 'pasta', 'pasta'),
(256, 'seasoned breadcrumbs', 'seasoned breadcrumb'),
(257, 'reduced fat mozzarella cheese', 'reduced fat mozzarella cheese'),
(258, 'marinara or Filetto di Pomodoro', 'marinara or Filetto di Pomodoro'),
(259, 'homemade enchilada sauce', 'homemade enchilada sauce'),
(260, 'large', 'large'),
(261, 'shredded Mexican cheese blend', 'shredded Mexican cheese blend'),
(262, 'sour cream', 'sour cream'),
(263, 'high fiber elbows like Ronzoni Smart Taste', 'high fiber elbows like Ronzoni Smart Taste'),
(264, 'skim milk', 'skim milk'),
(265, '2 cups reduced-fat sharp cheddar (Cabot 50%)', '2 cups reduced-fat sharp cheddar (Cabot 50%)'),
(266, 'seasoned bread crumbs', 'seasoned bread crumb'),
(267, 'good crusty bread', 'good crusty bread'),
(268, 'center cut bacon', 'center cut bacon'),
(269, 'jalapeños', 'jalapeño'),
(270, '1/3 less fat cream cheese', '1/3 less fat cream cheese'),
(271, 'reduced fat shredded cheddar jack', 'reduced fat shredded cheddar jack'),
(272, 'Italian seasoned whole wheat breadcrumbs', 'Italian seasoned whole wheat breadcrumb'),
(273, 'juicy limes', 'juicy lim'),
(274, 'sushi grade tuna', 'sushi grade tuna'),
(275, 'sriracha', 'sriracha'),
(276, 'toasted sesame seeds', 'toasted sesame seed'),
(277, 'Lime wedges', 'Lime wedg'),
(278, 'Reduced sodium soy or gluten-free tamari', 'Reduced sodium soy or gluten-free tamari'),
(279, 'Sriracha', 'Sriracha'),
(280, 'chopped Romaine', 'chopped Romaine'),
(281, 'crumbled blue cheese', 'crumbled blue cheese'),
(282, 'Homemade Blue Cheese Dressing', 'Homemade Blue Cheese Dressing'),
(283, 'turmeric', 'turmeric'),
(284, 'curry powder', 'curry powder'),
(285, 'red wine vinegar', 'red wine vinegar'),
(286, 'feta', 'feta'),
(287, 'Skinny Tzatziki', 'Skinny Tzatziki'),
(288, 'Dressing:', 'Dressing:'),
(289, 'Delallo''s 100% Organic Whole Wheat Elbow Past', 'Delallo''s 100% Organic Whole Wheat Elbow Past'),
(290, 'Cooking spray', 'Cooking spray'),
(291, 'low fat milk', 'low fat milk'),
(292, 'shredded part-skim mozzarella', 'shredded part-skim mozzarella'),
(293, 'proscuitto', 'proscuitto'),
(294, 'Burman’s Mayonnaise', 'Burman’s Mayonnaise'),
(295, 'soft taco-size Pueblo Lindo Flour Tortilla', 'soft taco-size Pueblo Lindo Flour Tortilla'),
(296, '1.5 oz Never Any! Oven Roasted Turkey', '1.5 oz Never Any! Oven Roasted Turkey'),
(297, 'hard boiled egg', 'hard boiled egg'),
(298, 'Happy Farms Cheese Snack Stick', 'Happy Farms Cheese Snack Stick'),
(299, 'batch homemade bagels', 'batch homemade bagel'),
(300, 'baking powder', 'baking powder'),
(301, '0% Stonyfield Greek yogurt', '0% Stonyfield Greek yogurt'),
(302, 'Pizza:', 'Pizza:'),
(303, 'pizza sauce', 'pizza sauce'),
(304, 'balsamic vinegar', 'balsamic vinegar'),
(305, 'grated Romano cheese', 'grated Romano cheese'),
(306, 'light Havarti cheese', 'light Havarti cheese'),
(307, 'low sodium or gluten-free soy sauce', 'low sodium or gluten-free soy sauce'),
(308, 'canola oil', 'canola oil'),
(309, 'bourbon', 'bourbon'),
(310, 'BBQ sauce', 'BBQ sauce'),
(311, 'whole roasted', 'whole roasted'),
(312, 'Feta cheese', 'Feta cheese'),
(313, 'fresh chopped dill', 'fresh chopped dill'),
(314, 'part skim mozzarella', 'part skim mozzarella'),
(315, 'fat free milk', 'fat free milk'),
(316, 'lamb loin chops', 'lamb loin chop'),
(317, 'Za’atar', 'Za’atar'),
(318, 'shaved Parmesan', 'shaved Parmesan'),
(319, 'balsamic glaze', 'balsamic glaze'),
(320, 'chopped romaine', 'chopped romaine'),
(321, 'genoa salami', 'genoa salami'),
(322, 'black beans', 'black bean'),
(323, 'juice of 1/2 lime', 'juice of 1/2 lime'),
(324, 'reduced fat Sargento Mexican Blend shredded cheese', 'reduced fat Sargento Mexican Blend shredded cheese'),
(325, 'beef', 'beef'),
(326, 'bamboo skewers', 'bamboo skewer'),
(327, 'light Hellman''s mayonnaise', 'light Hellman''s mayonnaise'),
(328, '0% Greek yogurt', '0% Greek yogurt'),
(329, 'Olive oil spray', 'Olive oil spray'),
(330, 'nutmeg', 'nutmeg'),
(331, 'vegetable oil', 'vegetable oil'),
(332, '1/3-less fat Philadelphia Cream Cheese', '1/3-less fat Philadelphia Cream Cheese'),
(333, 'original Earthly Grains Couscous', 'original Earthly Grains Couscou'),
(334, 'Carlini Olive Oil Cooking Spray', 'Carlini Olive Oil Cooking Spray'),
(335, 'Spinach Arugula Pesto', 'Spinach Arugula Pesto'),
(336, 'fresh packed SimplyNature Organic Baby Spinach & Arugula Mix', 'fresh packed SimplyNature Organic Baby Spinach & Arugula Mix'),
(337, 'grated Priano Parmesan', 'grated Priano Parmesan'),
(338, 'Stonemill Salt', 'Stonemill Salt'),
(339, 'Stonemill Ground Black Pepper', 'Stonemill Ground Black Pepper'),
(340, 'SimplyNature Extra Virgin Olive Oil', 'SimplyNature Extra Virgin Olive Oil'),
(341, 'mayo', 'mayo'),
(342, 'of parchment paper', 'of parchment paper'),
(343, 'Zest and juice from 1 medium lime', 'Zest and juice from 1 medium lime'),
(344, 'Dijon mustard', 'Dijon mustard'),
(345, 'mixed baby greens', 'mixed baby green'),
(346, 'store-bought tortilla strips', 'store-bought tortilla strip'),
(347, 'fresh live mussels', 'fresh live mussel'),
(348, 'medium lobster tails', 'medium lobster tail'),
(349, 'Herb Garlic Butter', 'Herb Garlic Butter'),
(350, 'Reynolds Kitchens Quick Cut Plastic Wrap', 'Reynolds Kitchens Quick Cut Plastic Wrap'),
(351, 'yellow mustard', 'yellow mustard'),
(352, 'fresh dill', 'fresh dill'),
(353, 'finely chopped dill pickle', 'finely chopped dill pickle'),
(354, 'pickle juice', 'pickle juice'),
(355, 'rice vinegar', 'rice vinegar'),
(356, '907 g flank steak', '907 g flank steak'),
(357, 'non-fat Greek yogurt', 'non-fat Greek yogurt'),
(358, 'whole egg', 'whole egg'),
(359, '1 1/2 oz shredded cheddar jack cheese', '1 1/2 oz shredded cheddar jack cheese'),
(360, 'low sodium soy sauce', 'low sodium soy sauce'),
(361, 'sesame seeds as garnish', 'sesame seeds as garnish'),
(362, 'Feta', 'Feta'),
(363, 'jumbo peeled and deveined shrimp', 'jumbo peeled and deveined shrimp'),
(364, 'whole wheat crusty bread', 'whole wheat crusty bread'),
(365, 'For the toppings:', 'For the toppings:'),
(366, 'jarred salsa', 'jarred salsa'),
(367, 'refrigerated Dough for 1', 'refrigerated Dough for 1'),
(368, 'part skim ricotta', 'part skim ricotta'),
(369, 'part skim shredded mozzarella', 'part skim shredded mozzarella'),
(370, 'semisweet chocolate chips', 'semisweet chocolate chip'),
(371, 'white vinegar', 'white vinegar'),
(372, '1% plain Greek yogurt', '1% plain Greek yogurt'),
(373, 'cooked quinoa', 'cooked quinoa'),
(374, 'ground pork', 'ground pork'),
(375, 'rice wine', 'rice wine'),
(376, 'low-sodium soy sauce', 'low-sodium soy sauce'),
(377, 'sesame seeds', 'sesame seed'),
(378, 'semi-sweet chocolate chips', 'semi-sweet chocolate chip'),
(379, 'Mexican Seasoning Mix', 'Mexican Seasoning Mix'),
(382, 'mozarella', 'mozarella'),
(383, 'caesar dressing', 'caesar dressing'),
(384, 'croutons', 'crouton'),
(385, 'virgin coconut oil', 'virgin coconut oil'),
(386, 'baking spray', 'baking spray'),
(387, 'mini chocolate chips', 'mini chocolate chip'),
(388, 'shredded cheese', 'shredded cheese'),
(389, 'long grain rice & wild rice combo', 'long grain rice & wild rice combo'),
(390, 'brown rice', 'brown rice'),
(391, 'mato', 'mato'),
(392, 'alcaparrado', 'alcaparrado'),
(393, 'ripe plantains', 'ripe plantain'),
(394, 'reduced fat shredded Mexican blend cheese', 'reduced fat shredded Mexican blend cheese');